import path from 'node:path';
import { XMLParser } from 'fast-xml-parser';
import * as parse5 from 'parse5';
import type { TocNode } from '../bookAdapter';
import { EpubFormatError, EpubSecurityError } from './epubErrors';
import { EpubArchive, normalizeArchivePath } from './epubArchive';

export interface EpubManifestItem { id: string; href: string; mediaType: string; properties: string[] }
export interface EpubSection { id: string; href: string; title?: string; order: number; progressionWeight: number }
export interface EpubPackage { opfPath: string; metadata: { title: string; authors: string[]; identifier?: string }; manifest: Map<string, EpubManifestItem>; sections: EpubSection[]; toc: TocNode[] }
const xml = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_', removeNSPrefix: true, textNodeName: '#text', trimValues: true });
export async function parseEpubPackage(archive: EpubArchive): Promise<EpubPackage> {
  const container = parseXml(await archive.readText('META-INF/container.xml'), 'container.xml');
  const rootfile = first(container?.container?.rootfiles?.rootfile); const opfPath = attr(rootfile, 'full-path'); if (!opfPath) throw new EpubFormatError('EPUB container has no rootfile.');
  const normalizedOpf = normalizeArchivePath(opfPath); const opf = parseXml(await archive.readText(normalizedOpf), 'OPF'); const pkg = opf?.package; if (!pkg) throw new EpubFormatError('Invalid EPUB package document.'); const base = path.posix.dirname(normalizedOpf);
  const manifest = new Map<string, EpubManifestItem>(); for (const item of array(pkg.manifest?.item)) { const id = attr(item, 'id'); const href = attr(item, 'href'); const mediaType = attr(item, 'media-type'); if (!id || !href || !mediaType) continue; manifest.set(id, { id, href: resolveInside(base, href.split('#')[0]), mediaType, properties: (attr(item, 'properties') ?? '').split(/\s+/).filter(Boolean) }); }
  const sections: EpubSection[] = []; for (const itemref of array(pkg.spine?.itemref)) { const id = attr(itemref, 'idref'); const item = id && manifest.get(id); if (item && archive.has(item.href)) { let weight = 1; try { weight = Math.max(1, stripMarkup(await archive.readText(item.href)).length); } catch {} sections.push({ id: item.id, href: item.href, order: sections.length, progressionWeight: weight }); } }
  if (!sections.length) throw new EpubFormatError('EPUB package has no readable spine.');
  const metadataNode = pkg.metadata ?? {}; const title = text(first(metadataNode.title)) || 'Untitled'; const authors = array(metadataNode.creator).map(text).filter(Boolean); const uniqueId = attr(pkg, 'unique-identifier'); const identifiers = array(metadataNode.identifier); const selectedId = identifiers.find((item) => attr(item, 'id') === uniqueId) ?? identifiers[0];
  const nav = [...manifest.values()].find((item) => item.properties.includes('nav')); let toc: TocNode[] = []; if (nav && archive.has(nav.href)) toc = parseNav(await archive.readText(nav.href), nav.href, sections);
  const ncxId = attr(pkg.spine, 'toc'); const ncx = ncxId && manifest.get(ncxId); if (!toc.length && ncx && archive.has(ncx.href)) toc = parseNcx(parseXml(await archive.readText(ncx.href), 'NCX'), ncx.href, sections);
  if (!toc.length) toc = sections.map((section) => ({ title: section.title ?? `Section ${section.order + 1}`, sectionId: section.id }));
  return { opfPath: normalizedOpf, metadata: { title, authors, ...(text(selectedId) ? { identifier: text(selectedId) } : {}) }, manifest, sections, toc };
}
function parseXml(source: string, label: string): any { if (/<!DOCTYPE|<!ENTITY/i.test(source)) throw new EpubSecurityError(`${label} contains forbidden DOCTYPE or ENTITY.`); try { return xml.parse(source); } catch (error) { throw new EpubFormatError(`Unable to parse ${label}: ${String(error)}`); } }
function parseNav(source: string, navPath: string, sections: EpubSection[]): TocNode[] { const doc: any = parse5.parse(source); let nav: any; walk(doc, (node) => { if (!nav && node.tagName === 'nav' && (getAttr(node, 'epub:type') === 'toc' || getAttr(node, 'type') === 'toc')) nav = node; }); const ol = nav?.childNodes?.find((x: any) => x.tagName === 'ol'); return ol ? parseOl(ol, navPath, sections) : []; }
function parseOl(ol: any, base: string, sections: EpubSection[]): TocNode[] { return (ol.childNodes ?? []).filter((x: any) => x.tagName === 'li').flatMap((li: any) => { let anchor: any; walk(li, (node) => { if (!anchor && node.tagName === 'a') anchor = node; }); if (!anchor) return []; const href = getAttr(anchor, 'href') ?? ''; const [file, fragment] = href.split('#'); const target = resolveInside(path.posix.dirname(base), file || path.posix.basename(base)); const section = sections.find((x) => x.href === target); if (!section) return []; const childOl = (li.childNodes ?? []).find((x: any) => x.tagName === 'ol'); return [{ title: nodeText(anchor).trim() || section.id, sectionId: section.id, ...(fragment ? { fragment } : {}), ...(childOl ? { children: parseOl(childOl, base, sections) } : {}) }]; }); }
function parseNcx(doc: any, ncxPath: string, sections: EpubSection[]): TocNode[] { const points = array(doc?.ncx?.navMap?.navPoint); const convert = (point: any): TocNode | undefined => { const src = attr(point.content, 'src') ?? ''; const [file, fragment] = src.split('#'); const section = sections.find((x) => x.href === resolveInside(path.posix.dirname(ncxPath), file)); if (!section) return undefined; const children = array(point.navPoint).map(convert).filter(Boolean) as TocNode[]; return { title: text(point.navLabel?.text) || section.id, sectionId: section.id, ...(fragment ? { fragment } : {}), ...(children.length ? { children } : {}) }; }; return points.map(convert).filter(Boolean) as TocNode[]; }
function resolveInside(base: string, href: string): string { const decoded = decodeURIComponent(href); return normalizeArchivePath(path.posix.normalize(path.posix.join(base === '.' ? '' : base, decoded))); }
function first<T>(value: T | T[]): T | undefined { return Array.isArray(value) ? value[0] : value; } function array<T>(value: T | T[] | undefined): T[] { return value === undefined ? [] : Array.isArray(value) ? value : [value]; }
function attr(value: any, name: string): string | undefined { const result = value?.[`@_${name}`]; return typeof result === 'string' ? result : undefined; } function text(value: any): string { if (typeof value === 'string' || typeof value === 'number') return String(value); return typeof value?.['#text'] === 'string' ? value['#text'] : ''; }
function walk(node: any, visit: (node: any) => void) { visit(node); for (const child of node.childNodes ?? []) walk(child, visit); } function getAttr(node: any, name: string) { return node.attrs?.find((x: any) => x.name === name || `${x.prefix}:${x.name}` === name)?.value; } function nodeText(node: any): string { return node.nodeName === '#text' ? node.value : (node.childNodes ?? []).map(nodeText).join(''); } function stripMarkup(value: string): string { return value.replace(/<[^>]*>/g, '').replace(/\s+/g, ' '); }
